#!/usr/bin/env python3
"""Builds the first-paint banner faces (ADR 0083, src/boot/banner-faces.ts).

index.html draws the start page banner (the starfield and the MUME /
COCKPIT wordmark) before the app has loaded (src/boot/first-paint.ts). The
app's own @font-face rules are `font-display: block` and their files are
100 KB or more, so the first paint cannot use them. Instead each regular
face that draws a banner glyph is cut down to just those glyphs, and the
subsets are embedded (base64 WOFF2) in the inline first-paint script. The
script registers the subsets of the selected family's stack under their
own names, so they never stand in for the app's faces.

A subset keeps the face's advance widths, units per em and vertical
metrics, so the glyphs sit exactly where the full face puts them. Hinting
(TrueType instructions) is most of a subset's bytes: about 2.5 KB with it,
0.5 KB without. Where the system hints (Linux, Windows), an unhinted block
glyph's top and bottom edges land on fractional pixels, a faint extra row
of pixels that the hinted full face does not draw. So the faces of the
default family (Hack) and of the legacy default and fallback (DejaVu Sans
Mono, which also draws the `✧` stars of most families) keep their
hinting, and the hand-over to the app's banner is pixel-identical with
them; the other families' subsets are unhinted (macOS and iOS draw no
hints anyway).

    BANNER_CHARS  the banner's glyphs (src/chrome/banner-data.ts), the
                  space between them, and the loader track's `░`

Dependency (build time only), as for scripts/build-fill-fonts.py:

    python3 -m venv /tmp/wc-font && /tmp/wc-font/bin/pip install fonttools==4.66.1 brotli==1.2.0
    /tmp/wc-font/bin/python scripts/build-banner-faces.py

The output is reproducible with the same fontTools / brotli versions.
"""

import base64
import io
import pathlib

from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = pathlib.Path(__file__).resolve().parent.parent
FONTS = ROOT / "public" / "fonts"
OUT = ROOT / "src" / "boot" / "banner-faces.ts"

# Keep in step with tests/unit/first-paint.test.ts (the banner's glyphs).
BANNER_CHARS = " █▄▀░✧·◦"

# The faces whose subsets keep their hinting (see above).
HINTED = {"Hack-Regular.woff2", "DejaVuSansMono.woff2"}


def regular_files():
    """Every regular face under public/fonts (the banner is never bold)."""
    for f in sorted(FONTS.glob("*.woff2")):
        if "-Bold" in f.name:
            continue
        yield f


def cut(path, chars, hinting):
    font = TTFont(path, recalcTimestamp=False)
    opt = subset.Options()
    opt.flavor = "woff2"
    opt.hinting = hinting
    opt.name_IDs = []
    opt.name_languages = []
    opt.layout_features = []
    opt.notdef_outline = False
    opt.glyph_names = False
    opt.recalc_timestamp = False
    opt.drop_tables += ["GSUB", "GPOS", "GDEF", "DSIG", "meta", "FFTM", "TTFA"]
    sub = subset.Subsetter(opt)
    sub.populate(text=chars)
    sub.subset(font)
    font.flavor = "woff2"
    buf = io.BytesIO()
    font.save(buf)
    return buf.getvalue()


def main():
    rows = []
    total = 0
    for f in regular_files():
        cmap = TTFont(f, lazy=True).getBestCmap()
        chars = "".join(c for c in BANNER_CHARS if ord(c) in cmap)
        if not chars.strip():
            continue
        data = cut(f, chars, f.name in HINTED)
        total += len(data)
        rows.append((f.name, chars, base64.b64encode(data).decode("ascii")))
    lines = [
        "// Generated by scripts/build-banner-faces.py (ADR 0083); do not edit.",
        "// The banner glyphs of each regular face under public/fonts, as WOFF2",
        "// subsets for the first paint (src/boot/first-paint.ts).",
        "",
        f"export const BANNER_CHARS = {BANNER_CHARS!r};".replace("'", "'"),
        "",
        "export interface BannerFace {",
        "  /** The characters the subset draws. */",
        "  chars: string;",
        "  /** The WOFF2 file, base64. */",
        "  woff2: string;",
        "}",
        "",
        "/** By the file name of the full face under public/fonts. */",
        "export const BANNER_FACES: Readonly<Record<string, BannerFace>> = {",
    ]
    for name, chars, b64 in rows:
        lines.append(f"  '{name}': {{ chars: '{chars}', woff2: '{b64}' }},")
    lines.append("};")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{OUT.relative_to(ROOT)}: {len(rows)} faces, {total} bytes of WOFF2")


if __name__ == "__main__":
    main()
